language: ruby
rvm:
  - 2.3.0
  - 2.2.4
bundler_args: --jobs=2
script:
  - bundle exec rails db:setup
  - bundle exec rspec
cache: bundler
addons:
  code_climate:
    repo_token: d9e823041f81b17d1a2d83c860bf93ba89e68d3776ddf1ec1958569c7a708cf0
